matrix:
  include:
  - os: linux
    env:
    - MAKE="make"
  - os: windows
    env:
    - MAKE="mingw32-make"

language: cpp


script:
- eval "${MAKE}"
- eval "${MAKE}" test

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jan200101"
  - git config --local user.email "sentrycraft123@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    "VVAVBr31TAhay4HQW6Ty6fMvCAi9M2Sx+hkqlorzcRFHfCLJm+yjYxaercpbFJMwDmLoGHMikLNKRO3Tn+vESuCrnXk6qoq6f5AUjY2pvrVMohcW25HVerJSWJpKh8FBsj+paznpjvMnntJJ8hQNIfROnhl1TgtOfvAiDUQPbZJQmnC8nvda+gMZyPJoaEBtA1bBqXUvqAW+4xZupgamaTZTi+SLU712HHI9fEsrMvsOnQBUCl5RegMeTLd5TX6GDeFzUZ9gkqD7tDtxI2CnwEZnrck5/5RcN0fNasoEUenYzybwd+AZADfP96Wbabukh6DPyR14tpPvg3LIyVaYuurTPWjxVPzjyMQW1OND6mrEvgwXDKx7yr770JFXoB76Q7EDkmXa9mIaGk9EY7F4pJuUni/pD/YQJAU702qd/u8St/FyhyiDQp+j+5zgiXFOHQnaDWBXXjH1ei932DJXhHKtffDVi1dTnbJPb6dbJJ1TOWKxfNHYqWk7jQIMNhhHCpv0RzPrAREMMbWmXnqUeOjgllKRmSaePMZnC3xVVHCjnb4CvvdeesX4UOC2SALeMP9RU5oCBOl+jLaoWy8t9bKT3S998tZbPdLdof4Eau5CTXBejbFeCclJIaUZ393S29ayDmVSLfWCmqfJrGgrLVU6ZjDhA6GD4EbFvq4GaLs="
  skip_cleanup: true
  draft: false
  file_glob: true
  file: bin/Release/*
  on:
    repo: Jan200101/textadventure
    branch: rise
    tags: true
